
version: "3"
services:
  db:
   image: mariadb:latest
   networks:
     - monreseau 

  
  flask:

    image: exo3/latest

    ports:
      - 5000:5000

    depends_on:
     - db
    networks:
     - monreseau


networks:
  monreseau:
