---
apiVersion: v1
kind: Namespace
metadata:
  name: exo3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-web
  namespace: exo3
spec:
  selector:
    matchLabels:
      app: exo3
  template:
    metadata:
      labels:
        app: exo3
    spec:
      containers:
      - name: exo3
        image: alio/exo3

---
apiVersion: v1
kind: Service
metadata:
  name: web-serv
  namespace: exo3
spec:
  type: NodePort
  selector:
    app: exo3
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 5150
    protocol: TCP
---

---
apiVersion: v1
kind: Pod
metadata:
  namespace: exo3
  name: mariadb-base
  labels:
    app: mariadb

spec:
  containers:
  - name: mariadb-app
    image: mariadb:latest
    resources:
      requests:
        memory: "250Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "750m"
    
  volumes:
  - name: mariadb-volume
    persistentVolumeClaim:
      claimName: mariadb-volume

---
apiVersion: v1
kind: Service
metadata:
  namespace: exo3
  name: mariadb

spec:
  type: ClusterIP 
  selector:
    app: mariadb
  ports:
  - targetPort: 3306
    port: 3306
    protocol: TCP


